// import './globals.css';
// import type { Metadata } from 'next';
// import { Inter, Belleza, Asset } from 'next/font/google';
// import { AuthProvider } from '@/context/authContext';

// const inter = Inter({ subsets: ['latin'] });
// export const belezza = Belleza({ weight: '400', subsets: ['latin'] });
// export const asset = Asset({ weight: '400', subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en scroll-smooth">
      <body /* className={inter.className} */>
        oi
        {/* <AuthProvider>{children}</AuthProvider> */}
      </body>
    </html>
  );
}
